# This is a basic workflow to help you get started with Actions

name: "Test pilot CI"

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Test Pilot
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
            java-version: '8'
            distribution: 'adopt'

      - name: Run test
        run: mvn --batch-mode --update-snapshots clean install -Dgeb.env=prod -Dapp.browser=hub-chrome -Dapp.envName=prod -Dapp.platform=prod -DhubUrl=http://3.9.178.223:4444/wd/hub/
        if: ${{ always() }}
      - uses: actions/upload-artifact@v2
        with:
          name: Report
          path:  /home/runner/work/Test_Pilot/Test_Pilot/target/Reports
          retention-days: 5
