# This is a basic workflow to help you get started with Actions

name: Test pilot CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Start Selenoid server
        uses: Xotabu4/selenoid-github-action@v1
        with:
          selenoid-start-arguments: |
            --args "-timeout 60s"

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Checkout the code
      - uses: actions/checkout@v2

      - name: Build with Maven
        uses: actions/set
        run: mvn --batch-mode --update-snapshots clean install




