name: "Single ID Automation tests run"
on:
  workflow_dispatch:
    inputs:

      branch:
        description: 'Branch Name'
        required: true
        default: 'sid-view-profile'
      browser:
        description: 'Browser'
        required: true
        default: 'chrome'

      env:
        required: true
        description: 'Environment Name'

      tags:
        required: true
        description: 'Test scenario tags'
      grid:
        description: 'Grid Url'
        required: true
        default: ''

      testExecution:
        description: 'Xray test execution ID'
        required : false
        default: 'XTP-11111'

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Single ID Automation Run
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Run test
        run: mvn clean install -U -f acceptance-tests/pom.xml -Denv=${{ github.event.inputs.env}} -Dapp.browser=${{ github.event.inputs.browser}} -Dapp.envName=prod -Dapp.platform=prod -DhubUrl=${{ github.event.inputs.grid }} -Dcucumber.options="--tags @${{ github.event.inputs.tags}}"

        if: always()

      - uses: actions/upload-artifact@v2
        with:
          name: Donut Report
          path: /home/runner/work/single-identity/single-identity/acceptance-tests/target/donut
          retention-days: 5


          #  - name: "Import results to Xray"
          # uses: mikepenz/xray-action@{latest-release}
          # with:
          #  username: ${{ secrets.JIRA_USERNAME }}
          # password: ${{ secrets.JIRA_PASSWORD }}
          #xrayCloud: "false"
          #xrayBaseUrl: ""
          #testFormat: "junit"
          #testPaths: "**/target/cucumber.json"
          #testExecKey: ${{ github.event.inputs.testExecution}}
